### ISSUE TITLE
Need tedious@2.6.4

### ISSUE THREAD

**Issue by amierhaider1** [auth0-extensions/canirequire#100]
### Package info

Package Name: tedious@2.6.4

Package Version: 2.6.4

Node Version: 7

### Reason for Request

I would like this package added because if I try to connect to SQL Server, I am getting following error:

 (node:7) [DEP0064] DeprecationWarning: tls.createSecurePair() is deprecated. Please use tls.TLSSocket instead.

**Comment by shawnmclean** [comment]
Hi, do you need 2.6.4? Can 6.6.2 help, that is here #98

**Comment by amierhaider1** [comment]
It is okay. I have already found the solution to login Azure SQL Server using current available version of tedious.

Thanks
