### ISSUE TITLE
Tedious upgrade

### ISSUE THREAD

**Issue by sandeepneerarambham** [auth0-extensions/canirequire#101]
### Package info

Package Name: tedious

Package Version: 

Node Version: 8

### Reason for Request

Attempting to do a SQL connection with our onPrem SQL.  We have the firewall configured and can connect to the server, however there is an issue with the tedious library.

It appears that Auth0 has tedious version 1.11 installed and there has been a change to the underlying node packages that has deprecated the TLS encryption.
https://github.com/tediousjs/tedious/issues/5

This means that we cannot connect to the server at all.
Is it possible to upgrade tedious?

**Comment by faroceann** [comment]
Hi there, `tedious@6.6.2` is available. This is the latest version. 
https://auth0-extensions.github.io/canirequire/#tedious

**Comment by lzychowski** [comment]
@sandeepneerarambham 

Version `6.6.2` should now be available.

Closing this request.
