### ISSUE TITLE
Request for log4js datadog appender

### ISSUE THREAD

**Issue by dimitrit** [auth0-extensions/canirequire#102]
### Package info

Package Name: @curve-technology/log4js-datadog

Package Version: 0.1.0

Node Version: 8

### Reason for Request
Our organisation uses Datadog to monitoring and analyse operational systems. Currently we have no visibility of our tenants as no Auth0 supported integrations are provided for Datadog. 
This package will allow us to send log events to the Datadog platform from rules and action scripts.

**Comment by shawnmclean** [comment]
This includes a peer dependency, which is a behavior that we do not support.
