### ISSUE TITLE
Update aws-sdk to v2.589.0

### ISSUE THREAD

**Issue by marcelotm2901** [auth0-extensions/canirequire#106]
### Package info

Package Name: aws-sdk

Package Version: v2.589.0

Node Version: 8

### Reason for Request

I would like this package added because I am working with Authentication Flow and managing complex scenarios for Emails and Templates outside of Auth0. 
The method "sendTemplatedEmail" is not available into the latest package version installed in Auth0 because it is 3 years old.

**Comment by shawnmclean** [comment]
A later version exists: `>= 2.593.0`
