### ISSUE TITLE
Upgrade to a supported Node version

### ISSUE THREAD

**Issue by Flambe** [auth0-extensions/canirequire#116]
### Reason for Request

Node 4 and Node 8 are no longer supported versions which means that we aren't even getting security updates: https://nodejs.org/en/about/releases/

Are there any plans to add support for Node 10/12? I would like to request a package, but it requires Node 10 at minimum.

**Comment by charlesjohnson** [comment]
At the moment Node 8 is the only supported version. Node 12 support is in-flight, and will be added in the coming weeks.

**Comment by seejee** [comment]
Hi there! Node 12 is available in all regions now. When you're ready to switch, you can change your Node runtime in the "Tenant Settings" dashboard configuration screen.

https://auth0.com/docs/dashboard/reference/settings-tenant#extensibility
