### ISSUE TITLE
Allow promise.allSettled

### ISSUE THREAD

**Issue by jtsampson** [auth0-extensions/canirequire#117]
### Package info

Package Name:  promise.allsettled

Package Version: 1.0.2

Node Version: 8

### Reason for Request

I would like this package added because...it allows easy integration of multipe service calls when merging user data from single tenent application model to a multi tennant modle via action scripts (instead of import/export which requires password change)

**Comment by seejee** [comment]
Hi there! Just to give you an update, the latest `promise.allsettled` package does not build in Node 8 any longer, but we'll be making this package available in our Node 12 runtime in the near future.
