### ISSUE TITLE
gitlab package available version is too old

### ISSUE THREAD

**Issue by saurabh-deep** [auth0-extensions/canirequire#118]
### Package info

Package Name: gitlab

Package Version: 14.2.2

Node Version: 8

### Reason for Request

I would like this package added because... the existing version available with Auth0 rules 3.4.2 is more than 2 years old.

**Comment by shawnmclean** [comment]
Hi @saurabh-deep, the `gitlab` package is  deprecated in favor of `@gitbeaker/node`. I'll be adding that instead. However, that package has dependencies that are only available on node 10 or higher. It will be added to the node 12 support when its released.

**Comment by saurabh-deep** [comment]
Sure @shawnmclean. When I created this request, `@gitbeaker/node` package didn't exist. But now since it is there, it makes total sense to add that in place of `gitlab`.

Appreciate you looking into this.

**Comment by seejee** [comment]
Hi @saurabh-deep, just wanted to let you know that `gitbreaker/node` is currently available in Node 12. If you haven't already done so, you can switch your Node runtime version in the "Tenant Settings" dashboard configuration page.

https://auth0.com/docs/dashboard/reference/settings-tenant#extensibility
