### ISSUE TITLE
update got

### ISSUE THREAD

**Issue by gagalago** [auth0-extensions/canirequire#124]
### Package info

Package Name:  [got](https://www.npmjs.com/package/got)

Package Version: 10.7.0

Node Version: 8

### Reason for Request

I would like this package added because the [changes from version 9 to 10](https://github.com/sindresorhus/got/releases/tag/v10.0.0) are quite big, so it will be easier to use the last version

**Comment by shawnmclean** [comment]
Hi @gagalago,

That version of got requires node 10 or higher. We're adding it to our node 12 when it becomes available.

**Comment by shawnmclean** [comment]
Node 12 support is coming soon with this package.
