### ISSUE TITLE
Get bent

### ISSUE THREAD

**Issue by Jiropole** [auth0-extensions/canirequire#125]
### Package info

Package Name: bent

Package Version: recent/latest, 7.1.2 at time of this writing

Node Version: 8

### Reason for Request

I would like this package added because...

`bent` is a successor to `request`, _by_ the maintainer of `request`, who has actively deprecated `request` for reasons explained [here](https://github.com/request/request/issues/3142).

**Comment by seejee** [comment]
Thanks! We will include this in the next release.
