### ISSUE TITLE
mongo driver >=2.2.12

### ISSUE THREAD

**Issue by giulianf** [auth0-extensions/canirequire#13]
Hi,

Is it possible to have mongodb module more than 2.2.11?

Because 2.2.12 is compatible with Mongo db 3 till 3.4.

see ref:
[https://docs.mongodb.com/ecosystem/drivers/driver-compatibility-reference/#reference-compatibility-mongodb-node]

Thanks

**Comment by fyockm** [comment]
@giulianf is there a particular version that you need? `mongodb@latest` looks like `3.1.4`. will that work for you?
