### ISSUE TITLE
Sentry.io

### ISSUE THREAD

**Issue by headho** [auth0-extensions/canirequire#14]
It would be extremely helpful if sentry.io is available in web task.

Thanks.

**Comment by fyockm** [comment]
@headho could you please specify a particular module and version? Thanks.

**Comment by adrian-baker** [comment]
The current version is 4.3.0, which would work fine - https://www.npmjs.com/package/@sentry/browser .

**Comment by keabcape** [comment]
This is still relevant, it should rather be the `@sentry/node` option.

https://www.npmjs.com/package/@sentry/node
