### ISSUE TITLE
Request Module is Deprecated - Proposing Axios as the Replacement

### ISSUE THREAD

**Issue by brianhyder** [auth0-extensions/canirequire#141]
### Package info

Package Name: [axios](https://www.npmjs.com/package/axios)

Package Version: 0.19.2

Node Version: 8, 12

### Reason for Request

I would like this package added because the [request](https://github.com/request/request/issues/3142) module has been deprecated by its maintainers.  Axios would be a great addition because it is already a dependency of the [Auth0 SDK](https://www.npmjs.com/package/auth0) for Node.js.  

Thanks for the consideration!

**Comment by seejee** [comment]
Thank you, we will include this in the next release.
