### ISSUE TITLE
Ramda update

### ISSUE THREAD

**Issue by akime-** [auth0-extensions/canirequire#143]
### Package info

Package Name: Ramda

Package Version: 0.27.0 / latest

Node Version: 12

### Reason for Request

I would like this package added because the current extension version 0.23.0 released 3 years ago.

**Comment by seejee** [comment]
Thanks for opening this issue. Ramda 0.27.0 will be included in the next release. We'll close this issue once it is available.

**Comment by seejee** [comment]
This package is now available. Thanks again for the request!
