### ISSUE TITLE
support @azure/service-bus package

### ISSUE THREAD

**Issue by kamnel** [auth0-extensions/canirequire#144]
### Package info

Package Name: @azure/service-bus

Package Version: 1.1.7 / latest

Node Version: 12

### Reason for Request

I would like to use azure storage bus in Auth0 rules. Existing libraries like azure-sb are superseded by  @azure/service-bus by microsoft.

**Comment by seejee** [comment]
Thanks for opening this issue! `@azure/service-bus@1.1.7` will be included in the next release. We'll close this issue once it is available.

**Comment by seejee** [comment]
This package is now available. Thanks again for the request!
