### ISSUE TITLE
support @azure/storage-queue package

### ISSUE THREAD

**Issue by kamnel** [auth0-extensions/canirequire#145]
### Package info

Package Name: @azure/storage-queue

Package Version: 12.0.5/latest

Node Version: 12

### Reason for Request

I would like to use azure storage bus in Auth0 rules. Existing libraries like azure-storage are superseded by @azure/storage-queue

**Comment by seejee** [comment]
Thanks for opening this issue! `@azure/storage-queue@12.0.5` will be included in the next release. We'll close this issue once it is available.

**Comment by seejee** [comment]
This package is now available. Thanks again for the request!
