### ISSUE TITLE
nano update.

### ISSUE THREAD

**Issue by ssudaraka** [auth0-extensions/canirequire#147]
### Package info

Package Name: nano (https://www.npmjs.com/package/nano)

Package Version: 8.2.2

Node Version: 12

### Reason for Request

I would like this package added because the currently supported version (6.2.0) is updated 4 years ago.

**Comment by seejee** [comment]
Thanks for opening this issue! `nano@8.2.2` will be included in the next release. We'll close this issue once it is available.

**Comment by seejee** [comment]
This package is now available. Thanks again for the request!
