### ISSUE TITLE
Add the office 'authorizenet' npm module to rules

### ISSUE THREAD

**Issue by nabeards** [auth0-extensions/canirequire#148]
### Package info

Package Name: authorizenet

Package Version: 1.0.7

Node Version: 12

### Reason for Request

I would like this package so access the official authorize.net API for adding metadata to users after login.

**Comment by seejee** [comment]
Thanks for opening this issue! `authorizenet@1.0.7` will be included in the next release. We'll close this issue once it is available.

**Comment by seejee** [comment]
This package is now available. Thanks again for the request!

**Comment by nabeards** [comment]
Fantastic, thank you @seejee !
