### ISSUE TITLE
Got v11.3.0

### ISSUE THREAD

**Issue by rynecheow** [auth0-extensions/canirequire#149]
### Package info

Package Name: Got

Package Version: v11.3.0

Node Version: 10/12

https://github.com/sindresorhus/got/releases/tag/v11.3.0

### Reason for Request

I would like this package added because needed it as a replacement for `request` and the latest major version today is still v10.

**Comment by seejee** [comment]
Thanks for opening this issue! `got@11.3.0` will be included in the next release. We'll close this issue once it is available.

**Comment by seejee** [comment]
This package is now available. Thanks again for the request!
