### ISSUE TITLE
sumologic npm module

### ISSUE THREAD

**Issue by abbaspour** [auth0-extensions/canirequire#15]
Please add sumologic to available modules. 
package: sumo-logger

**Comment by villeodell** [comment]
Sumo Logic has an official library for node, probably better to use that one: 

- https://www.npmjs.com/package/sumo-logger
- https://github.com/SumoLogic/js-sumo-logger

**Comment by abbaspour** [comment]
raised https://auth0team.atlassian.net/browse/EX-1247

**Comment by fyockm** [comment]
`sumo-logger@1.5.5` has been added
