### ISSUE TITLE
@hapi/joi@17.1.1

### ISSUE THREAD

**Issue by robbiemccorkell** [auth0-extensions/canirequire#150]
### Package info

Package Name: @hapi/joi

Package Version: 17.1.1

Node Version: 12

### Reason for Request

The current versions of Joi available are now deprecated and the latest version of the package lives under the Hapi organisation: https://www.npmjs.com/package/@hapi/joi

In general Joi is used for validating a JSON object to a typed schema. It's very useful for server side validation within Auth0 rules for things like form submissions.

**Comment by seejee** [comment]
Thanks for opening this issue! `@hapi/joi@17.1.1` will be included in the next release. We'll close this issue once it is available.

**Comment by seejee** [comment]
This package is now available. Thanks again for the request!

**Comment by robbiemccorkell** [comment]
Super helpful, thank you
