### ISSUE TITLE
@hubspot/api-client 2.0.1

### ISSUE THREAD

**Issue by josephpage** [auth0-extensions/canirequire#155]
### Package info

Package Name: [@hubspot/api-client](https://www.npmjs.com/package/@hubspot/api-client)

Package Version: 2.0.1

Node Version: 12

### Reason for Request

I would like to automate the import and sync of my users with my CRM through hooks.

**Comment by luisbritos** [comment]
Hello @josephpage, thanks for opening this issue! @hubspot/api-client@2.0.1 will be included in the next release. We'll close this issue once it is available.
