### ISSUE TITLE
disposable-email-domains 1.0.56

### ISSUE THREAD

**Issue by Geschan** [auth0-extensions/canirequire#156]
### Package info

Package Name: [disposable-email-domains ](https://www.npmjs.com/package/disposable-email-domains)

Package Version: 1.0.56

Node Version: 12

### Reason for Request

I would like this package added/updated because I'd like to block the latest disposable email domains from sign-up/sign-in.

**Comment by Geschan** [comment]
Also it would be nice if this package/list will reveive updates regularly as the list of disposable email domains grows fast

**Comment by luisbritos** [comment]
Hello @Geschan, thanks for opening this issue! `disposable-email-domains@1.0.56` will be included in the next release. We'll close this issue once it is available.
