### ISSUE TITLE
get-ip-range @2.1.0

### ISSUE THREAD

**Issue by paul-barilla-1** [auth0-extensions/canirequire#157]
### Package info

Package Name: 
get-ip-range

Package Version: 
2.1.0

Node Version: 8

### Reason for Request

I would like this package added because... I need to get the valid ipv6 range from two ipv6 addresses (min, max)

**Comment by seejee** [comment]
Hi there! We will release support for this package in a few days. Just to let you know, since Node 8 has gone out of official support this package will only be available in Node 12 and above. Please let us know if that's a problem for you. Thanks for submitting the request!
