### ISSUE TITLE
Got v11.5.1 for Node 8/10/12

### ISSUE THREAD

**Issue by rynecheow** [auth0-extensions/canirequire#159]
### Package info

Package Name: Got

Package Version: v11.5.1

Node Version: 8/10/12

https://github.com/sindresorhus/got/releases/tag/v11.5.1

### Reason for Request

I would like this package added because of better fetch mechanism in webtask

**Comment by seejee** [comment]
Hi there! We will release support for this package to the public cloud in a few days. Just to let you know, since Node 8 has gone out of official support this package will only be available in Node 12 and above. Please let us know if that's a problem for you. Thanks for submitting this request!

**Comment by rynecheow** [comment]
Thanks!

**Comment by seejee** [comment]
We tried to backport this to Node 8 as well, but unfortunately, it looks like `got` only supports Node 10 and above starting with major version 10. But this is available now in Node 12 in our public cloud environments.
