### ISSUE TITLE
google-libphonenumber v3.2.10 for Node 8/10/12

### ISSUE THREAD

**Issue by rynecheow** [auth0-extensions/canirequire#161]
### Package info

Package Name: google-libphonenumber

Package Version: v3.2.10

Node Version: 8/10/12

https://github.com/ruimarinho/google-libphonenumber/releases/tag/v3.2.10

### Reason for Request

I would like this package added because of better phone number formatting mechanism in webtask

**Comment by seejee** [comment]
Hi there! We will release support for this package to the public cloud in a few days. Just to let you know, since Node 8 has gone out of official support, this package will only be available in Node 12 and above. Please let us know if that's a problem for you. Thanks for submitting this request!

**Comment by rynecheow** [comment]
Thanks!

**Comment by seejee** [comment]
This has been released in our public cloud environments for both Node 8 and Node 12 environments. Thanks for submitting the issue!
