### ISSUE TITLE
lodash v4.17.19 for Node 8/10/12

### ISSUE THREAD

**Issue by rynecheow** [auth0-extensions/canirequire#162]
### Package info

Package Name: lodash

Package Version: v4.17.19

Node Version: 8/10/12

https://github.com/lodash/lodash/releases/tag/4.17.19

### Reason for Request

I would like this package added because of better object manipulation in webtask

**Comment by seejee** [comment]
Hi there! I'm closing this because lodash 4.17.19 is already available in both Node 8 and Node 12.
