### ISSUE TITLE
Auth0-extensions(node js library)

### ISSUE THREAD

**Issue by NazariiKostiuk** [auth0-extensions/canirequire#164]
### Package info

Package Name: filter-object

Package Version: 3.0.0

Node Version: 12

### Reason for Request

I would like this package added because there is an older version installed (@2.1.0) but it doesn't have necessary features in order to filter objects by its keys or values for node js in auth0 tenant

**Comment by seejee** [comment]
Hi there! We will release support for this package in a few days. Thanks for submitting the request!

**Comment by NazariiKostiuk** [comment]
Hello @seejee,

I'm sorry, any update on this request?

Best Regards,
Nazarii

**Comment by NazariiKostiuk** [comment]
Hello @seejee,

I already see the required package on the auth0-extensions page. 
I think I can close the issue. Thanks a lot for that.

Best Regards,
Nazarii

**Comment by NazariiKostiuk** [comment]
Hello @seejee,

I'm not sure that I can close the issue on my own.

I already see the necessary package on the auth0-extensions. Thanks a lot for that.

Best Regards,
Nazarii

**Comment by seejee** [comment]
No problem! Thanks again.
