### ISSUE TITLE
hmac and hashlib for Intercom identity verification

### ISSUE THREAD

**Issue by phoebexy** [auth0-extensions/canirequire#165]
### Package info

Package Name: hmac, hashlib

Package Version: 

Node Version: 8

### Reason for Request

I would like this package added to perform Intercom identity verification

**Comment by seejee** [comment]
Hi there! Thanks for submitting the issue. The packages you requested are quite old, and there should be native support for creating hmacs and doing Hashing in [the Nodejs Crypto library](https://nodejs.org/docs/latest-v12.x/api/crypto.html). If the builtin Node.js functionality is not sufficient, would you mind adding a little more detail about why so we can understand your use case?

Thanks in advance!

**Comment by seejee** [comment]
I'm going to close this issue. Please let us know if you feel strongly that these should be included.
