### ISSUE TITLE
Duo Web

### ISSUE THREAD

**Issue by Rashaine-Johnson** [auth0-extensions/canirequire#166]
### Package info

Package Name: 
Duo Web
Package Version: 
1.0.5
Node Version: 12
https://www.npmjs.com/package/@duosecurity/duo_web

### Reason for Request

I would like this package added because...
Sign Duo requests and verify responses.

**Comment by seejee** [comment]
Thanks for opening the issue. We'll make this package available with our next release in the next few days. I'll update the status here to `released` when it's available.
