### ISSUE TITLE
Request Form: snowflake-sdk

### ISSUE THREAD

**Issue by maciejkulinski** [auth0-extensions/canirequire#167]
### Package info

Package Name: snowflake-sdk

Package Version: 1.5.2

Node Version: 12

### Reason for Request

We use Snowflake as our main DB solution and would like to explore solutions for using it as custom database connection in Auth0.

**Comment by seejee** [comment]
Thanks for opening the issue. We'll make this package available with our next release in the next few days. I'll update the status here to `released` when it's available.
