### ISSUE TITLE
Airgram module

### ISSUE THREAD

**Issue by leog** [auth0-extensions/canirequire#168]
I would like to use Airgram module in order to get a user authenticated with Telegram through a rule to invite them to specific private groups depending on their role stored in their appdata.

**Comment by seejee** [comment]
Thanks for opening the issue. We'll make this package available in our Node 12 environment with our next release in the next few days. I'll update the status here to `released` when it's available.

**Comment by leog** [comment]
@seejee @shawnmclean thank you for the quick action here. I was wondering if there is a chance to switch `airgram` with `@mtproto/core` as that is the definitive way to work with Telegram API. Otherwise I will also need you to follow these instructions to have `airgram` available: https://airgram.io/guides/installation. Thanks a lot in advance.
