### ISSUE TITLE
Tedious version 8.3.0+

### ISSUE THREAD

**Issue by okeegan-myob** [auth0-extensions/canirequire#171]
### Package info

Package Name:  [Tedious JS](https://github.com/tediousjs/tedious)

Package Version: 8.3.0 or above

Node Version: 12

### Reason for Request

We would like to take advantages of various bug fixes and improvements in later versions. (Currently Auth0-extensions supports versions 6.6.2, 1.11.0 and 0.1.4)

**Comment by seejee** [comment]
Thanks for opening the issue. We'll make this `8.3.1` and `9.2.1` available with our next release in the next few days. I'll update the status here to released when it's available.

**Comment by okeegan-myob** [comment]
Hi @seejee, how did you go with this one?

**Comment by shawnmclean** [comment]
Hey @okeegan-myob, this is still in progress. We're estimating by the end of the week for this to hit US region.

**Comment by okeegan-myob** [comment]
Hi @shawnmclean, @seejee - any news? 😸 

edit: AH! I see it has been updated. Thank you! Closing! 😁
