### ISSUE TITLE
firebase-admin v9.x

### ISSUE THREAD

**Issue by myktra** [auth0-extensions/canirequire#172]
### Package info

Package Name: `firebase-admin`
Package Version: 9.1.1
Node Version: 12

### Reason for Request

Version 9.x of this package has upgraded dependencies to Firebase's *Firestore* and *Storage* APIs which include important enhancements and fixes that improve the overall stability of the Firebase API experience.

Thanks!!!

**Comment by myktra** [comment]
Note: this version of `firebase-admin` no longer supports Node 8. If this is a showstopper, I'd request at least upgrading `firebase-admin` to v8.13.0.

**Comment by shawnmclean** [comment]
Hi @myktra 8.13.0 will be available to node 8 tenants and 9.1.1 on node 12. It should be in US region by end of week.
