### ISSUE TITLE
Add jsonwebtoken to available modules

### ISSUE THREAD

**Issue by ysle** [auth0-extensions/canirequire#185]
### Package info

Package Name: jsonwebtoken

Package Version: 8.5.1

NPM Url: https://www.npmjs.com/package/jsonwebtoken

### Reason for Request

I would like this package added because we need to sign a jwt token as part of our Auth0 flow as well, so not just decode it please.

**Comment by hedwigz** [comment]
This package is already available afaik: https://auth0-extensions.github.io/canirequire/#jsonwebtoken

**Comment by ysle** [comment]
oh, my mistake. thanks for the info 👍
