### ISSUE TITLE
Update to version 3.3.0 of graphql-request

### ISSUE THREAD

**Issue by paulvonallwoerden** [auth0-extensions/canirequire#189]
### Package info

Package Name: 
graphql-request

Package Version: 
3.3.0

NPM Url: 
https://www.npmjs.com/package/graphql-request

### Reason for Request

I would like this package added because the current version (1.8.2) is from 2018 and is missing some neat features that have been added over the time.

Some of the new features I would appreciate to use:

- https://github.com/prisma-labs/graphql-request/pull/212
- https://github.com/prisma-labs/graphql-request/pull/175
- https://github.com/prisma-labs/graphql-request/commit/c2253f2b44b223671a32a273cf47b26a66d29cfe

**Comment by shawnmclean** [comment]
Hi @paulvonallwoerden, sorry we can't add this. Packages with a peer dependency aren't supported with this method.
