### ISSUE TITLE
Support recent versions of the `auth0` module

### ISSUE THREAD

**Issue by lkoskela** [auth0-extensions/canirequire#21]
It's somewhat strange that Auth0 doesn't support recent versions of its own `auth0` module – especially the one that many rules need.

Right now, the availability on a sandbox Auth0 tenant seem to be:

- `auth0@2.7.0` is available
- `auth0@2.7.1` is NOT available
- `auth0@2.8.0` is available
- `auth0@2.9.0` is NOT available
- `auth0@2.9.1` is available
- `auth0@2.10.0` is NOT available
- `auth0@2.11.0` is NOT available
- `auth0@2.12.0` is NOT available

It's also a bit weird that the Node 4 runtime would support `auth0@2.12.0` but upgrading to Node 8 runtime suddenly you're back to a 10-month old version (`auth0@2.9.1`).

**Comment by fyockm** [comment]
`auth0@2.13.0` is available in both Node 4 and Node 8
