### ISSUE TITLE
Datadog metrics for NodeJS scripts

### ISSUE THREAD

**Issue by tpires** [auth0-extensions/canirequire#219]
### Package info

Package Name: datadog-metrics

Package Version: 0.8.2

NPM Url: https://www.npmjs.com/package/datadog-metrics

### Reason for Request

I would like this package added because atm the only way to set up metrics is via logs to custom metrics option, and it isn't a scalable option. Thank you.

**Comment by seejee** [comment]
👋  We've included this in our next release, and we hope to get it out in the next few days. Thanks for the request!

**Comment by tpires** [comment]
thank you @seejee!
