### ISSUE TITLE
Upgrade graphql-request@1.8.2 -> @3.4.0 please

### ISSUE THREAD

**Issue by gjolund** [auth0-extensions/canirequire#221]
### Package info

Package Name: graphql-request

Package Version: 3.4.0

NPM Url: https://www.npmjs.com/package/graphql-request

### Reason for Request

The current version on canirequire is @1.8.2, which is almost 2 years old.

https://auth0-extensions.github.io/canirequire/#graphql-request

The new version includes security, performance, and quality of life updates and would make using gql within rules much easier.

**Comment by seejee** [comment]
Thanks for your submission. I just wanted to give an update on this: the way that `graphql-request` declares a `peerDependency` on `graphql` is making it a little tricky for us to embed this package in our Rules runtime. We're trying to find a workaround and appreciate your patience.

I was able to use `graphql-request` in our new Actions feature without any issues (as long as `graphql` is also added as a dependency), so depending on your needs perhaps Actions will work for you. Thanks again!

**Comment by gjolund** [comment]
> Thanks for your submission. I just wanted to give an update on this: the way that `graphql-request` declares a `peerDependency` on `graphql` is making it a little tricky for us to embed this package in our Rules runtime. We're trying to find a workaround and appreciate your patience.
> 
> I was able to use `graphql-request` in our new Actions feature without any issues (as long as `graphql` is also added as a dependency), so depending on your needs perhaps Actions will work for you. Thanks again!

We are currently using it in production too without issue.

The biggest issue I have right now is that the currently available version of gql-request doesn't have a types available and we are using @ts-check + jsdoc to type check our rules.

This means I have to exclude the gql client from type checking which is less than ideal. We have a similar problem with the auth0 mgmt lib, but I can raise that in a separate issue.
