### ISSUE TITLE
oauth-1.0a

### ISSUE THREAD

**Issue by cincy0312** [auth0-extensions/canirequire#232]
### Package info:oauth-1.0a

Package Name: oauth-1.0a

Package Version: 1.0

NPM Url: 
https://www.npmjs.com/package/oauth-1.0a

### Reason for Request:Netsuite Restlet api-Authenticate

I would like this package added because,I would like to use oauth-1.0a in custom database login script to authenticate netsuite restlet api.

**Comment by jpadilla** [comment]
We've included oauth-1.0a@2.2.6
