### ISSUE TITLE
Update request-promise to fix security vulnerability in transitive dependency lodash

### ISSUE THREAD

**Issue by arjenvanderende** [auth0-extensions/canirequire#24]
According to `npm audit` module `request-promise@1.0.2` contains a security vulnerability in the transitive dependency `lodash`. In later versions, the library was rewritten to no longer use `lodash` so it's no longer an issue. For more info about the vulnerability see: https://www.npmjs.com/advisories/577

Is it possible to add a more recent version of the `request-promise` library, for instance the latest version 4.2.2?

**Comment by fyockm** [comment]
Sorry, the newer version of `request-promise` has a peer dependency on `request`, and will not build in our environment. Please consider using a different library.
