### ISSUE TITLE
Please add Couchbase to the supported modules!

### ISSUE THREAD

**Issue by ejscribner** [auth0-extensions/canirequire#274]
### Package info

Package Name: couchbase

Package Version: 3.2.1

NPM Url: https://www.npmjs.com/package/couchbase

### Reason for Request

I would like this package added because I want to use Couchbase as my auth database. Couchbase offers an award-winning distributed NoSQL cloud database with unmatched versatility, performance, and scalability. Enabling the use of Couchbase on Auth0 out-of-the-box provides users with another powerful option for storing their authentication data.

**Comment by jpadilla** [comment]
We're not able to add support for this dependency at this moment.

**Comment by ejscribner** [comment]
Wondering if any context can be given as to why not? Lack of interest?
