### ISSUE TITLE
package-request - glob-intersection

### ISSUE THREAD

**Issue by jandppw** [auth0-extensions/canirequire#28]
used to determine whether one glob pattern is a subset of another

we use it to determine whether we can issue a requested resource action authorization, given resource action mandates

**Comment by jandppw** [comment]
Yes, it is relevant. Since there has been no human answer, there is nothing blocking it. There is nothing I can do from this end.

**Comment by fyockm** [comment]
@jandppw sorry for the delay. `glob-intersection@0.1.3` has been added to the node 8 build.
