### ISSUE TITLE
support for jose@3.18.0

### ISSUE THREAD

**Issue by vikasjayaram** [auth0-extensions/canirequire#282]
### Package info

Package Name: jose

Package Version: 3.18.0

NPM Url: https://github.com/panva/jose

### Reason for Request

I would like this package added because need to support validation ES alg in auth0 extensibility.

**Comment by turcottedanny** [comment]
Closing this one in favor of the more recent one: https://github.com/auth0-extensions/canirequire/issues/287 (3.19.0)
