### ISSUE TITLE
Axios - 0.21.3

### ISSUE THREAD

**Issue by DannyPat44** [auth0-extensions/canirequire#285]
### Package info

Package Name: axios

Package Version: 0.21.3

NPM Url: https://www.npmjs.com/package/axios

### Reason for Request

We are requesting this package to address the following vulnerability that we have silenced in our Scanner for the time being. https://app.snyk.io/vuln/SNYK-JS-AXIOS-1579269

**Comment by filipatavares** [comment]
I was just about to create the same request.
Thanks @DannyPat44 !
