### ISSUE TITLE
jose v3.19.0

### ISSUE THREAD

**Issue by rynecheow** [auth0-extensions/canirequire#287]
### Package info

Package Name: jose

Package Version: 3.19.0

NPM Url: https://www.npmjs.com/package/jose

### Reason for Request

I would like this package added because of better performance cryptic exchange within rules and tasks

**Comment by panva** [comment]
I'd recommend to pull in v4.0.2 and leave v3.x behind. Pretty much the only thing to migrate is changing the import/require statements.

```
// before (v3.x)
import { jwtVerify } from 'jose/jwt/verify'
import { SignJWT } from 'jose/jwt/sign'

// after (v4.x)
import { jwtVerify, SignJWT } from 'jose'
```

**Comment by rynecheow** [comment]
Makes sense - thanks
