### ISSUE TITLE
update google packages

### ISSUE THREAD

**Issue by luisrudge** [auth0-extensions/canirequire#29]
I'm sure there's more of them, but I did find those very outdated packages:

#### Auth0

```
require('google-auth-library@1.0.0')
require('googleapis@2.1.6')
```

#### NPM
```
"google-auth-library": "^2.0.0",
"googleapis": "^34.0.0",
```

**Comment by fyockm** [comment]
Done

**Comment by villeodell** [comment]
Can we get these added also?

- @google-cloud/datastore - 2.0.0
- @google-cloud/firestore - 0.19.0
- @google-cloud/kms - 0.2.0
- @google-cloud/monitoring - 0.6.0
- @google-cloud/pubsub - 0.22.0
- @google-cloud/logging - 4.1.0
- @google-cloud/logging-bunyan - 0.9.4
- @google-cloud/logging-winston - 0.10.2
- @google-cloud/storage - 2.3.1

### Reason for Request

From the meta [googleapis](https://github.com/googleapis/google-api-nodejs-client#working-with-google-cloud-platform-apis):

> **Working with Google Cloud Platform APIs?** 
> If you're working with Google Cloud Platform APIs such as Datastore, Cloud Storage or Pub/Sub, consider using the `@google-cloud` client libraries: single purpose idiomatic Node.js clients for Google Cloud Platform services.
> 
> **Support and maintenance** 
> These client libraries are official supported by Google. However, these libraries are considered complete and are in maintenance mode. This means that we will address critical bugs and security issues ***but will not add any new features.*** 
> 
> ***For Google Cloud Platform APIs, we recommend using [google-cloud-node](https://github.com/GoogleCloudPlatform/google-cloud-node) which is under active development.***
