### ISSUE TITLE
envkey

### ISSUE THREAD

**Issue by saenzramiro** [auth0-extensions/canirequire#3]
This amazing service helps us to manage the ENV variables using an easy UI, instead of defining in the `configuration.{key}`.

https://www.npmjs.com/package/envkey

**Comment by fyockm** [comment]
@saenzramiro sorry, maybe I'm missing something. I don't quite understand how this would work with Auth0 Rules or Custom DB scripts?

**Comment by villeodell** [comment]
I think the desire is just to have access to a way of centrally managing secrets. 

For example: 
- all secrets (api keys, etc.) are hosted envkey.com
- generate an "envkey" secret to load from envkey.com, (perhaps specific to auth0 that limits which secrets can be retreived?)
- use the envkey package inside auth0 rules -- e.g. `require('envkey')` `process.env.ENVKEY = 'my-env-key';`
- it loads all your secrets from envkey.com as env variables available to the rule

Not necessarily more secure, but dynamically loading the secrets from a centralized brings some benefits (e.g. if a secret changes just update at envkey.com and you're done) and envkey.com looks low effort to use.

@saenzramiro:
You might want to check out [AWS secrets manager](https://aws.amazon.com/secrets-manager/) along with [aws-sdk](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SecretsManager.html) for node to achieve basically the same thing as what you'd get with envkey.

And for something a little more involved, but also a lot more secure (your actual secrets are never exposed externally): https://medium.com/poka-techblog/the-best-way-to-store-secrets-in-your-app-is-not-to-store-secrets-in-your-app-308a6807d3ed
