### ISSUE TITLE
Please add the neo4j-driver library

### ISSUE THREAD

**Issue by thepechinator** [auth0-extensions/canirequire#30]
https://github.com/neo4j/neo4j-javascript-driver

This library helps us work with the neo4j graph database. Thanks.

**Comment by thepechinator** [comment]
Yes, this is still relevant.

**Comment by ggoodman** [comment]
Version `1.7.1` of this module is available in node8 runtimes.

**Comment by thepechinator** [comment]
Awesome, thanks!
