### ISSUE TITLE
Need to add Sinch SDK to deliver SMS MFA Messages

### ISSUE THREAD

**Issue by sandeepneerarambham** [auth0-extensions/canirequire#307]
### Package info

Package Name: sinch-rtc

Package Version: Latest 1.4.12

NPM Url: https://www.npmjs.com/package/sinch-rtc

### Reason for Request

I would like this package added because a customer wants to use Sinch to send SMS messages.

**Comment by turcottedanny** [comment]
This package doesn't work with Node 12
