### ISSUE TITLE
Request for webtask-tools

### ISSUE THREAD

**Issue by SumanaMalkapuram** [auth0-extensions/canirequire#31]
Request for webtask-tools package

**Comment by fyockm** [comment]
@SumanaMalkapuram `webtask-tools` is actually built into the underlying platform, and therefore does not show up on canirequire. However, it _IS_ available via Auth0 Extensibility.

**Comment by SumanaMalkapuram** [comment]
Awesome. Thank you so much for confirming back. 

Thanks,
Sumana
