### ISSUE TITLE
Additional modules for Auth0 snowflake

### ISSUE THREAD

**Issue by Danco626** [auth0-extensions/canirequire#331]
### Package info

Package Name: 

- async-retry
- i18n
- node-cache

Package Version: 

- "async-retry": "^1.3.3",
- "i18n": "^0.15.0",
- "node-cache": "^5.1.2",

NPM Url: 
[async-retry](https://www.npmjs.com/package/async-retry)
[i18n](https://www.npmjs.com/package/i18n)
[node-cache](https://www.npmjs.com/package/node-cache)

### Reason for Request

I would like this package added because I'm a member of the Auth0 professional services team whose currently working on a few snowflakes for a customer. The snow flakes require these packages for 
- retrying failed API calls to the MFA API
- caching user factors 
- supporting both the  English and Spanish languages

**Comment by wtwerner** [comment]
Please disregard, related to a bug that has since been fixed.
