### ISSUE TITLE
Additional modules for Auth0 snowflake Pt. 2

### ISSUE THREAD

**Issue by Danco626** [auth0-extensions/canirequire#333]
### Package info

Package Name:      

-   auth0
-   axios
-   dotenv
-   ejs
-   express
-   express-openid-connect
-   jsonwebtoken
-   jwks-rsa
-   pino
-   uuid
-   lodash
-   moment
-   morgan
-    jose

Package Version: 

-   auth0: 2.42.0
-   axios: 0.27.2
-   dotenv: 16.0.3
-   ejs: 3.1.8
-   express: 4.18.1
-   express-openid-connect: 2.8.0
-   jsonwebtoken: 8.5.1
-   jwks-rsa: 2.1.4
-   pino: 8.6.1
-   uuid: 9.0.0
-   lodash: 4.17.21
-   moment: 2.29.4
-   morgan: 1.10.0
-    jose: 4.10.0

NPM Url: 
-   [auth0](https://www.npmjs.com/package/auth0)
-   [axios](https://www.npmjs.com/package/axios)
-   [dotenv](https://www.npmjs.com/package/dotenv)
-   [ejs](https://www.npmjs.com/package/ejs)
-   [express](https://www.npmjs.com/package/express)
-   [express-openid-connect](https://www.npmjs.com/package/express-openid-connect)
-   [jsonwebtoken](https://www.npmjs.com/package/jsonwebtoken)
-   [jwks-rsa](https://www.npmjs.com/package/jwks-rsa)
-   [pino](https://www.npmjs.com/package/pino)
-   [uuid](https://www.npmjs.com/package/uuid)
-   [lodash](https://www.npmjs.com/package/lodash)
-   [moment](https://www.npmjs.com/package/moment)
-   [morgan](https://www.npmjs.com/package/morgan)
-   [jose](https://www.npmjs.com/package/jose)

### Reason for Request
I would like this package added because I'm a member of the Auth0 professional services team whose currently working on a few snowflakes for a customer. 

Earlier releases of these packages are already available however due to deprecations we've had to change our code after downgrading.

**Comment by wtwerner** [comment]
Please disregard these modules, this was in response to a bug that has been fixed.
