### ISSUE TITLE
Add pacakge launchdarkly-js-client-sdk 

### ISSUE THREAD

**Issue by wdfbordin** [auth0-extensions/canirequire#334]
### Package info

Package Name: 
launchdarkly-js-client-sdk

Package Version:
 2.23.0

NPM Url: 
https://www.npmjs.com/package/launchdarkly-js-client-sdk

### Reason for Request

I would like this package added because I need to try Launchdarkly to do a progressive implementation of MFA of our clients.

**Comment by johneke-auth0** [comment]
@wdfbordin [launchdarkly-js-client-sdk](https://www.npmjs.com/package/launchdarkly-js-client-sdk) is a browser only package and wont work in our `nodejs` environment according to the docs. Is this the right package? We can't really add this guy based on the comment that its browser only.

From the npm page:

```
Note: If you are using JavaScript in a non-browser environment, please see our [server-side Node.js SDK](https://github.com/launchdarkly/node-server-sdk), [client-side Node.js SDK](https://github.com/launchdarkly/node-client-sdk), and [Electron SDK](https://github.com/launchdarkly/electron-client-sdk).
```
