### ISSUE TITLE
datadog-metrics 0.10.2

### ISSUE THREAD

**Issue by artstupels** [auth0-extensions/canirequire#335]
### Package info

Package Name: datadog-metrics

Package Version: 0.10.2

NPM Url: https://www.npmjs.com/package/datadog-metrics

### Reason for Request

There's a huge difference between these two: since 0.10.2 datadog-metrics deprecated the agent and imported the official datadog-metrics-client, which is much more performant.

**Comment by emmaLP** [comment]
Will version 0.10.2 be available for Node12 auth0 rules?

Also, is there an eta of when this will be available?
