### ISSUE TITLE
npm version upgrade for jsonwebtoken

### ISSUE THREAD

**Issue by muditsrivastav3007** [auth0-extensions/canirequire#345]
### Package info

Package Name: jsonwebtoken

Package Version: 9.0.0

NPM Url: https://www.npmjs.com/package/jsonwebtoken

### Reason for Request

I would like this package added because... version 8.5.0 has some security concerns

**Comment by KKamishima** [comment]
dup #342

**Comment by muditsrivastav3007** [comment]
any timelines for this to be taken care ?

**Comment by KKamishima** [comment]
Now it is available, apparently.
