### ISSUE TITLE
@aws-sdk/client-sts

### ISSUE THREAD

**Issue by jsmylnycky** [auth0-extensions/canirequire#348]
### Package info

Package Name: `@aws-sdk/client-sts`

Package Version: `3.282.0`

NPM Url: https://www.npmjs.com/package/@aws-sdk/client-sts

### Reason for Request

I would like this package added because I need to be able to leverage "assume role" for my migration scripts from Cognito

**Comment by TwelveNights** [comment]
Hi @jsmylnycky, @aws-sdk/client-sts@3.287.0 has been released. Please let us know if your older version of this library is instead required.
