### ISSUE TITLE
@aws-sdk/client-cognito-identity-provider

### ISSUE THREAD

**Issue by jsmylnycky** [auth0-extensions/canirequire#349]
### Package info

Package Name: `@aws-sdk/client-cognito-identity-provider`

Package Version: `3.282.0`

NPM Url: https://www.npmjs.com/package/@aws-sdk/client-cognito-identity-provider

### Reason for Request

I would like this package added because I need to be able to leverage "AdminGetUserCommand" for my migration scripts from Cognito to get the profile details about the migrating user (getUser script)

**Comment by TwelveNights** [comment]
Hi @jsmylnycky, `@aws-sdk/client-cognito-identity-provider@3.287.0` has been released. Please let us know if your older version of this library is instead required.
