### ISSUE TITLE
dayjs

### ISSUE THREAD

**Issue by seankelly001** [auth0-extensions/canirequire#350]
### Package info

Package Name: dayjs

Package Version: 1.11.7

NPM Url: https://www.npmjs.com/package/dayjs

### Reason for Request

I would like this package added because day.js is a lightweight and modern replacement to moment.js, which has many issues and is not recommended to use anymore.

**Comment by TwelveNights** [comment]
Hi @seankelly001, `dayjs@1.11.7` has been released.
