### ISSUE TITLE
mongodb@5.1.0

### ISSUE THREAD

**Issue by shinkhouse** [auth0-extensions/canirequire#352]
### Package info

Package Name: mongodb

Package Version: 5.1.0

NPM Url: https://www.npmjs.com/package/mongodb/v/5.1.0

### Reason for Request

I would like this package added because the last version of the mongodb client supported by auth0 seems to be 4.1.0, which is already over two years old. Could we please have a more up to date version of the library supported, such as 5.x.x? 

https://www.mongodb.com/docs/drivers/node/current/compatibility/

**Comment by TwelveNights** [comment]
Hi @shinkhouse, `mongodb@5.1.0` has been released.
