### ISSUE TITLE
Request to add @sanity/client npm package for Auth0 Rules

### ISSUE THREAD

**Issue by imriShCodeArt** [auth0-extensions/canirequire#353]
### Package info

Package Name: @sanity/client

Package Version: 5.4.2

NPM Url: https://www.npmjs.com/package/@sanity/client

### Reason for Request

I would like this package added because I am using Sanity CMS to store additional user data such as firstName, lastName, and metadata. I need to integrate Auth0 with Sanity CMS, and to achieve this, I have created an Auth0 Rule that interacts with the Sanity API to store and update user information when a user logs in.

The @sanity/client package provides a convenient way to interact with Sanity's API, allowing me to easily create and update user data in Sanity CMS. This package is well-maintained and widely used within the Sanity community. Adding this package would enable seamless integration between Auth0 and Sanity CMS, benefiting developers who want to use Sanity as a data store for their Auth0-authenticated applications.

Thank you for considering my request.

**Comment by TwelveNights** [comment]
Hi @imriShCodeArt, `@sanity/client@5.4.2` has been released.
