### ISSUE TITLE
Axios 1.6.2

### ISSUE THREAD

**Issue by sionl** [auth0-extensions/canirequire#368]
### Package info

Package Name: axios

Package Version: 1.6.2

NPM Url: https://www.npmjs.com/package/axios/v/1.6.2

### Reason for Request

I would like this package added because I want to use the latest version

**Comment by bendiknesbo** [comment]
+1 for this. Axios 1.4.0 (the newest available in canirequire) has a security vulnerability: https://github.com/advisories/GHSA-wf5p-g6vw-rhxx

**Comment by TwelveNights** [comment]
`1.6.5` is now available in the node 16 and 18 runtimes :blush:
