### ISSUE TITLE
Require AMQP Javascript library.

### ISSUE THREAD

**Issue by jethoraz** [auth0-extensions/canirequire#37]
### Package info

Package Name: node-amqp

Package Version: 0.2.7

Node Version: 8

### Reason for Request

I would like this package added because we need to propagate user creation events to a persistent queue. There is already an accepted mqtt library in the "can I require" section, but mqtt has very limited functionality for getting backlog of missed MQ messages, and also only supports topics, and not queues.

**Comment by fyockm** [comment]
@jethoraz `node-amqp@0.2.7` is quite old. `1.2.1` is the most recent version. any reason you requested that particular version?

**Comment by jethoraz** [comment]
Hello,

Not any particular reason other than it was the one npm threw at me, when isearched for an amqp js library, and it was only 4 months old, and have 16.000 downloads a week.

I’m a Java developer per se, and not all up to speed on js, but we need to connect to an AWS ActiveMQ using the AMQP protocol.

Any amqp library that you can approve should do the trick really.

I have added my client as cc to this nail, to keep him in the loop.

Thank you
Martin

Sendt fra min iPhone
