### ISSUE TITLE
package-requirest virgil-sdk and virgil-crypto

### ISSUE THREAD

**Issue by xlewkanx** [auth0-extensions/canirequire#38]
### Package info 

Package Name: virgil-sdk

Package Version: 5.2.0

Node Version: 8

### Package info 

Package Name: virgil-crypto

Package Version: 3.2.0

Node Version: 8

### Reason for Request

I would like this packages added because we can integrate Auth0 and Virgil Security seamlessly with your hooks. Users will have opportunity implement End-to-End Encryption powered by our cloud services and open source sdk and crypto in easier way.

**Comment by fyockm** [comment]
@xlwknx we are evaluating these packages

**Comment by xlewkanx** [comment]
@fyockm Hi, how it is going, any updates?

**Comment by xlewkanx** [comment]
Hi @fyockm
We are still waiting for result of your review.
