### ISSUE TITLE
UUID 3.3.x with version 5 UUID support

### ISSUE THREAD

**Issue by dmark** [auth0-extensions/canirequire#39]
### Package info

Package Name: uuid

Package Version: 3.3.x

Node Version: 8

### Reason for Request

I would like this package added because I would like to be able to generate version 5 namespace based UUIDs in Auth0.

**Comment by fyockm** [comment]
`uuid@3.3.2` has been added to the for Node 8

**Comment by dmark** [comment]
Probably the wrong place to ask, but does anyone know if there's an issue using the "slash version" syntax in Auth0 rules / webstask.io?

```
  const uuid = require('uuid@3.3.2');
```

works, but 

```
  const uuid = require('uuid@3.3.2/v5');
```

per the docs gets:

```
ERROR: Cannot find module 'uuid@3.3.2/v5'
```

`uuid` or `uuid@3.3.2` defaults to version 4 I believe, which is fine, but I was hoping to use version 5 namespace based UUIDs.
