### ISSUE TITLE
"Slash" syntax in module import doesn't work? (uuid module)

### ISSUE THREAD

**Issue by dmark** [auth0-extensions/canirequire#41]
ref: https://community.auth0.com/t/error-cannot-find-module-uuid-v5/17880

Probably the wrong place to ask, but does anyone know if there's an issue using the "slash version" syntax in Auth0 rules / webstask.io?

```
  const uuid = require('uuid');
```

works, but 

```
  const uuid = require('uuid/v5');
```

per the docs gets:

```
ERROR: Cannot find module 'uuid/v5'
```

`uuid` or `uuid@3.3.2` defaults to version 4 I believe, which is fine, but I was hoping to use version 5 namespace based UUIDs.

**Comment by fyockm** [comment]
@dmark slash syntax does not currently work in auth0 rules or webtask.io. we are currently evaluating a workaround, and will keep you posted when it is available.

**Comment by dmark** [comment]
Thanks @fyockm.
