### ISSUE TITLE
Require new AMQP javascript library

### ISSUE THREAD

**Issue by jethoraz** [auth0-extensions/canirequire#44]
### Package info

Package Name: amqplib

Package Version: 0.5.3

Node Version: 8

### Reason for Request

We previously had the amqp library approved for auth0, but it turns out, that their implementation of SSL/TLS connections to amqp server is incompatible with the way Auth0 manages libraries (need for ca-certs file). Amqplib solves this by being able to use a byte-buffer for ca-cert instead of only accepting a local path. We need TLS, as we send user info to our AMQP broker via the internet.

**Comment by fyockm** [comment]
`amqplib@0.5.3` has been added to the node 8 build.
