### ISSUE TITLE
jsonwebtoken

### ISSUE THREAD

**Issue by DimitriLubenski** [auth0-extensions/canirequire#50]
## ✏️ Request Form

Currently jsonwebtoken@7.1.9 is supported in the rules and fetch profiles. The version is very old (+3 years) and should get an update because of security considerations.

### Package info

Package Name: jsonwebtoken

Package Version: 8.5.0

Node Version: 8

### Reason for Request

I would like this package added because...

**Comment by gcallaghan** [comment]
Why is this a wontfix?

**Comment by shawnmclean** [comment]
@gcallaghan sorry the bot flagged it. We have added this.
