### ISSUE TITLE
auth0@2.17.0

### ISSUE THREAD

**Issue by Shadlington** [auth0-extensions/canirequire#56]
### Package info

Package Name: node-auth0

Package Version: 2.17.0

Node Version: 8

### Reason for Request

I would like this package added because 2.17.0 added support for user roles and permissions, which I would like access to. Thanks.

**Comment by magnus-eriksson-k** [comment]
Also a request from me for managing user roles

**Comment by stratton** [comment]
Pretty frustrating that Auth0 is so far out of date when it comes to supporting their own libraries.

**Comment by nkohari** [comment]
This package has been available for a little while. Sorry for the lack of communication, and thanks!
