### ISSUE TITLE
Request for meteor-sha256

### ISSUE THREAD

**Issue by LaChips** [auth0-extensions/canirequire#58]
### Package info

Package Name: meteor-sha256

Package Version: 1.0.1

Node Version: 8

### Reason for Request

I believe Meteor uses a slight different implementation of sha256 encryption. I can't figure out how to match the password on login because I can't get the same hash. With this package, I could get the same sha256 encryption method and be able to match passwords easily.

But if you know how I could do it without having to add this package, that would be appreciated :)

**Comment by shawnmclean** [comment]
This was added. Please ignore the bot.
