### ISSUE TITLE
Package Request for Adobe Analytics DI

### ISSUE THREAD

**Issue by a139763** [auth0-extensions/canirequire#62]
### Package info

Package Name: Adobe-Analytics-DI

https://www.npmjs.com/package/adobe-analytics-di

Package Version: 1.3

Node Version: 8

### Reason for Request

I would like this package added because I want to send data to our adobe analytics reporting server upons successful / unsuccessful logins

**Comment by nkohari** [comment]
This has been completed, thanks!
