### ISSUE TITLE
Stripe@7.1.0

### ISSUE THREAD

**Issue by byrneciaran** [auth0-extensions/canirequire#66]
### Package info

Package Name: Stripe

Package Version: 7.1.0

Node Version: 8

### Reason for Request

The package you support has deprecated API's, and is several versions behind Stripes API. Specifically the Subscriptions API.

**Comment by thfuchs** [comment]
I'd like to add using the [current latest version](https://www.npmjs.com/package/stripe) once this issue is handled.  
At the moment: 7.4.0

**Comment by shawnmclean** [comment]
7.4.0 was added.
