### ISSUE TITLE
request amazon-cognito-identity-js

### ISSUE THREAD

**Issue by da7oom20** [auth0-extensions/canirequire#67]
## ✏️ Request Form
Hi, I need amazon-cognito-identity-js package to be added since I need to use it in custom DB with cognito
### Package info
https://www.npmjs.com/package/amazon-cognito-identity-js
Package Name: 
amazon-cognito-identity-
Package Version: 
latest
Node Version: 8

### Reason for Request

I would like this package added because i am trying to migrate cognito and Auth0, so the users data in cognito and my application is running in Auth0

**Comment by shawnmclean** [comment]
This is added.
