### ISSUE TITLE
Request for Amazon DAX Client

### ISSUE THREAD

**Issue by jin09** [auth0-extensions/canirequire#68]
## ✏️ Request Form
Hi, need this package to connect to AWS DAX cluster with DynamoDB

### Package info

https://www.npmjs.com/package/amazon-dax-client
Package Name: amazon-dax-client

Package Version: 1.2.2 

Node Version: 8

### Reason for Request

I would like this package added because I want to use caching with DynamoDB and DAX is the recommended way to go ahead. I am storing some permission specific stuff in Dynamo which needs to be put in the token everytime a user makes a login request. I dont want Auth0 to keep hitting Dynamo on each request, want to make it more efficient using DAX as cache in between.

**Comment by shawnmclean** [comment]
This is added.
