### ISSUE TITLE
apollo

### ISSUE THREAD

**Issue by dryhurst** [auth0-extensions/canirequire#70]
we need apollo packages installed please. 

apollo-boost or these individual packages. 

apollo-client: Where all the magic happens
apollo-cache-inmemory: Our recommended cache
apollo-link-http: An Apollo Link for remote data fetching
apollo-link-error: An Apollo Link for error handling
apollo-link-state: An Apollo Link for local state management
graphql-tag: Exports the gql function for your queries & mutations

**Comment by shawnmclean** [comment]
This is added.
