### ISSUE TITLE
Update the getstream package

### ISSUE THREAD

**Issue by aaroncampos** [auth0-extensions/canirequire#71]
### Package info

Package Name: getstream

Package Version: 4.2.2

Node Version: 8

### Reason for Request

I would like this package added because the version you currently have added is out of date.  Thanks!

**Comment by jawgardner** [comment]
Not only is it out of date, it is unusable at present, because createUserToken is not available in the v3.x package in the sandbox. Please help.

**Comment by shawnmclean** [comment]
This is added.

**Comment by aaroncampos** [comment]
Awesome, thanks!
