### ISSUE TITLE
Is Auth0 still supporting this?

### ISSUE THREAD

**Issue by mindofjonas** [auth0-extensions/canirequire#75]
Looking at the list of current issues it looks like many of the Node modules Auth0 Rules supports are way out of date and aren't being updated. Example: `stripe` is still at v4.24.0 and even Auth0's `auth0` library hasn't been update. 

Additionally there are quite a few open issues with requests for new modules that haven't been responded to in in quite a while.

**Comment by charlesjohnson** [comment]
Hi @mindofjonas!

Thanks for your patience.

As part of our project to end-of-life node4 support on the Auth0 platform, we temporarily paused merging requests from this repo. That work should wrap in the next few days, and merging of issues in this repo will resume again in August.
