### ISSUE TITLE
Lightweight GraphQL client: graphql-request

### ISSUE THREAD

**Issue by TAnas0** [auth0-extensions/canirequire#77]
### Package info

Package Name: [graphql-request](https://github.com/prisma/graphql-request)

Package Version: 1.8.2 

Node Version: 8

### Reason for Request

I would like this package added because I noticed that there is a lack of GraphQL client and libraries to be used from the Auth0 rules.
This could be useful for saving data to the database on user signups for example, or in making API requests in general.

The package suggested seems a good fit to the Auth0 rules environment, since it is lightweight and simplistic, compared to the Apollo suite, which is much more extensive.

I just switched to Rules from Hooks because my hook does not get triggered on social logins, and I noticed a big difference between both environments. In Auth0 Hooks, we have access to most public NPM modules, but to my understanding Hooks are ran on the Webtask environment, which is more advanced.

Anyways, if you happen to have recommendations specific to my use-case, that would be awesome too.

Cheers

**Comment by shawnmclean** [comment]
This is added.
