### ISSUE TITLE
Update firebase-admin to 6.0.0

### ISSUE THREAD

**Issue by nimonian** [auth0-extensions/canirequire#8]
The latest `firebase-admin@6.0.0` so that we can use Cloud Firestore with a service account.

[https://www.npmjs.com/package/firebase-admin](https://www.npmjs.com/package/firebase-admin)

I understand from another ticket the latest `firebase` is in progress so I suppose this should be fine too.

**Comment by fyockm** [comment]
`firebase@0.5.4` was added - does that cover your use case?

**Comment by nimonian** [comment]
I don't think so.  `firebase` and `firebase-admin` are different libraries, as far as I know `firebase-admin` is designed for use on the server as opposed to in an app, and it is definitely `firebase-admin` which I need.

The most recent version of `firebase-admin` I can use in Auth0 Rules is `5.0.0`  but we need `6.0.0` to get important new features.

**Comment by villeodell** [comment]
This was added.
