### ISSUE TITLE
Add Infusionsoft SDK

### ISSUE THREAD

**Issue by anjosh-zz** [auth0-extensions/canirequire#81]
### Package info

Package Name: infusionsoft_rest_api

Package Version: 0.03

Node Version: 8

### Reason for Request

I would like this package added because I want to pull the contact id from my infusionsoft database and store it in user.app_metadata.

**Comment by shawnmclean** [comment]
`infusionsoft_rest_api` is actually `infusionsoft-sdk`. Would you still like this package to be added?

**Comment by anjosh-zz** [comment]
No the sdk didn't work for me so it is not necessary. I appreciate your reply.
