### ISSUE TITLE
googleapis@42.0.0

### ISSUE THREAD

**Issue by jelder** [auth0-extensions/canirequire#92]
### Package info

Package Name: googleapis

Package Version: 42.0.0

Node Version: 8

### Reason for Request

The oldest version of this package for which Google still publishes documentation is 40.0.0, so no reference material exists for the 36.0.0 version currently available. See https://www.googleapis.dev/nodejs/googleapis/latest

**Comment by shawnmclean** [comment]
@jelder latest is 43.0.0, will add this instead.
